version: 2.1

orbs:
  slack: circleci/slack@5.2.0

jobs:
  install:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Instalar dependencias
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - slack/notify:
          event: fail
          template: basic_fail_1

  lint:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Instalar dependencias
          command: npm ci
      - run:
          name: Ejecutar ESLint
          command: npm run lint
      - slack/notify:
          event: fail
          template: basic_fail_1

  test:
    docker:
      - image: cimg/node:20.18
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Instalar dependencias
          command: npm ci
      - run:
          name: Ejecutar pruebas en paralelo
          command: npm test
      - slack/notify:
          event: fail
          template: basic_fail_1

  build:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
            - npm-cache-
      - run:
          name: Instalar dependencias
          command: npm ci
      - run:
          name: Ejecutar build
          command: npm run build
      - slack/notify:
          event: pass
          template: basic_success_1
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  pipeline_calculadora:
    jobs:
      - install

      - lint:
          requires:
            - install

      - test:
          requires:
            - install

      - build:
          requires:
            - lint
            - test